# All Data

In [20]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='users')
users

,user_id,user_gender,user_age,country,location
0,a2474,Female,24,United Kingdom,New Mariomouth
1,14100000,Male,21,Germany,Danielsfort
2,34db0,Male,27,Australia,Vincentchester
3,20d08,Female,28,India,Lisaport
4,9e830,Male,28,United States,Brownmouth
...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside
9996,68b82,Male,24,Mexico,Brownland
9997,39f39,Male,29,United States,Watersburgh
9998,0b8e7,Male,31,United Kingdom,South Kenneth
9999,99e3f,Male,37,Canada,New Courtneyview

In [21]:
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ads')
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group
0,1,28,Facebook,Video,Female,35-44
1,2,33,Facebook,Stories,All,25-34
2,3,20,Instagram,Carousel,All,25-34
3,4,28,Facebook,Stories,Female,25-34
4,5,24,Instagram,Image,Female,25-34
...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44
196,197,9,Facebook,Stories,All,All
197,198,34,Facebook,Video,All,35-44
198,199,15,Instagram,Video,Male,25-34
199,200,44,Instagram,Carousel,Male,18-24

In [3]:
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='campaigns')
campaigns

,campaign_id,name,start_date,end_date,total_budget
0,1,Campaign_1_Launch,2025-03-25,2025-07-23,24021.32
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,79342.41
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,14343.25
3,4,Campaign_4_Summer,2025-04-04,2025-08-08,45326.60
4,5,Campaign_5_Launch,2025-05-11,2025-08-28,68376.69
5,6,Campaign_6_Winter,2025-04-21,2025-09-13,78607.49
6,7,Campaign_7_Winter,2025-03-25,2025-08-05,43744.59
7,8,Campaign_8_Q3,2025-02-25,2025-04-07,39953.19
8,9,Campaign_9_Launch,2025-03-25,2025-07-13,40094.07
9,10,Campaign_10_Winter,2025-03-17,2025-07-21,19669.27
10,11,Campaign_11_Q3,2025-04-24,2025-07-02,79067.91
11,12,Campaign_12_Q3,2025-03-08,2025-06-01,30525.65
12,13,Campaign_13_Winter,2025-04-19,2025-07-01,21855.42
13,14,Campaign_14_Summer,2025-04-15,2025-06-04,39849.94
14,15,Campaign_15_Launch,2025-03-21,2025-06-11,85407.23
15,16,Campaign_16_Winter,2025-03-07,2025-06-04,71521.88
16,17,Campaign_17_Launch,2025-04-22,2025-07-18,86675.92
17,18,Campaign_18_Q3,2025-04-19,2025-06-15,48832.61
18,19,Campaign_19_Winter,2025-03-06,2025-05-15,33182.45
19,20,Campaign_20_Winter,2025-02-17,2025-05-18,98904.66
20,21,Campaign_21_Winter,2025-04-19,2025-06-22,37290.81
21,22,Campaign_22_Q3,2025-03-17,2025-04-22,35743.40
22,23,Campaign_23_Winter,2025-05-10,2025-10-02,26001.67
23,24,Campaign_24_Summer,2025-03-30,2025-05-23,56692.87
24,25,Campaign_25_Winter,2025-04-07,2025-09-04,52725.49
25,26,Campaign_26_Winter,2025-04-01,2025-06-17,44538.87
26,27,Campaign_27_Q3,2025-02-13,2025-04-02,12986.30
27,28,Campaign_28_Winter,2025-03-09,2025-06-30,32844.79
28,29,Campaign_29_Winter,2025-05-16,2025-10-06,19773.66
29,30,Campaign_30_Winter,2025-02-25,2025-05-10,73911.29
30,31,Campaign_31_Summer,2025-03-27,2025-07-22,72208.34
31,32,Campaign_32_Summer,2025-05-02,2025-06-14,81744.53
32,33,Campaign_33_Summer,2025-04-08,2025-07-04,59264.68
33,34,Campaign_34_Winter,2025-05-10,2025-09-08,26104.30
34,35,Campaign_35_Launch,2025-05-23,2025-10-12,71626.83
35,36,Campaign_36_Q3,2025-03-07,2025-05-13,58801.99
36,37,Campaign_37_Launch,2025-03-18,2025-08-01,46445.20
37,38,Campaign_38_Q3,2025-04-21,2025-05-27,71038.28
38,39,Campaign_39_Q3,2025-03-18,2025-07-27,55638.18
39,40,Campaign_40_Summer,2025-03-04,2025-04-20,53936.41
40,41,Campaign_41_Winter,2025-04-02,2025-06-12,85220.35
41,42,Campaign_42_Summer,2025-04-08,2025-07-25,7918.04
42,43,Campaign_43_Winter,2025-04-23,2025-06-12,81350.30
43,44,Campaign_44_Q3,2025-05-14,2025-09-22,15914.87
44,45,Campaign_45_Summer,2025-03-26,2025-08-05,53303.55
45,46,Campaign_46_Winter,2025-03-10,2025-08-07,94023.76
46,47,Campaign_47_Launch,2025-04-17,2025-09-03,69493.36
47,48,Campaign_48_Winter,2025-04-08,2025-06-01,13842.07
48,49,Campaign_49_Winter,2025-02-21,2025-05-17,28962.34
49,50,Campaign_50_Summer,2025-05-02,2025-08-03,47274.70

In [20]:
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_events')
ad_events

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [21]:
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='interests')
interests

,interest_id,interest
0,1,art
1,2,technology
2,3,food
3,4,fitness
4,5,gaming
5,6,finance
6,7,lifestyle
7,8,travel
8,9,sports
9,10,health
10,11,news
11,12,fashion
12,13,photography

In [22]:
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='user_interest')
user_interest

,user_id,interest_id
0,a2474,4
1,a2474,10
2,14100000,3
3,14100000,4
4,14100000,7
...,...,...
19929,68b82,6
19930,39f39,10
19931,0b8e7,1
19932,0b8e7,12
19933,99e3f,4

In [23]:
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_interest')
ad_interest

,ad_id,interest_id
0,1,1
1,1,2
2,2,8
3,2,13
4,3,2
...,...,...
295,198,4
296,198,7
297,199,1
298,199,11
299,200,13

In [24]:
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='sub_interests')
sub_interests

,interest_id,interest_id_related
0,1,12
1,1,13
2,2,6
3,2,5
4,2,11
5,2,13
6,3,7
7,3,10
8,3,4
9,4,3
10,4,9
11,4,10
12,4,7
13,5,9
14,5,2
15,6,2
16,6,11
17,7,8
18,7,12
19,7,10
20,7,4
21,8,13
22,8,7
23,9,4
24,9,11
25,9,10
26,9,5
27,10,4
28,10,9
29,10,7
30,10,3
31,11,2
32,11,9
33,11,6
34,12,1
35,12,7
36,13,1
37,13,8
38,13,2

# Normalize Data

In [1]:
import pandas as pd
import numpy as np
!pip install xlrd
!pip install openpyxl

Requirement already satisfied: xlrd in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.0.2)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

Uplode user table

In [4]:
users = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='users')
users

,user_id,user_gender,user_age,country,location,interests
0,a2474,Female,24,United Kingdom,New Mariomouth,"fitness, health"
1,14100000,Male,21,Germany,Danielsfort,"food, fitness, lifestyle"
2,34db0,Male,27,Australia,Vincentchester,"fashion, news"
3,20d08,Female,28,India,Lisaport,"health, news, finance"
4,9e830,Male,28,United States,Brownmouth,"health, photography, lifestyle"
...,...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside,"travel, fashion, art"
9996,68b82,Male,24,Mexico,Brownland,finance
9997,39f39,Male,29,United States,Watersburgh,health
9998,0b8e7,Male,31,United Kingdom,South Kenneth,"art, fashion"
9999,99e3f,Male,37,Canada,New Courtneyview,fitness

Uplode Ads table

In [12]:
ads = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='ads')
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology
3,4,28,Facebook,Stories,Female,25-34,news
4,5,24,Instagram,Image,Female,25-34,news
...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,"gaming, sports"
196,197,9,Facebook,Stories,All,All,"lifestyle, gaming"
197,198,34,Facebook,Video,All,35-44,"fitness, lifestyle"
198,199,15,Instagram,Video,Male,25-34,"art, news"
199,200,44,Instagram,Carousel,Male,18-24,photography

In [14]:
def disttinct_intrests(interests):
    res = ", ".join(interests)
    return set(res.split(", "))

In [15]:
users_interests = disttinct_intrests(users['interests'])
ads_interests = disttinct_intrests(ads['target_interests'])
all_interests = users_interests | ads_interests

interests = pd.DataFrame({'interest_id': range(1, len(all_interests) + 1), 'interest': list(all_interests)})
interests

,interest_id,interest
0,1,travel
1,2,news
2,3,lifestyle
3,4,sports
4,5,fashion
5,6,fitness
6,7,food
7,8,health
8,9,photography
9,10,finance
10,11,art
11,12,technology
12,13,gaming

In [16]:
def create_interests_fact_table(dim_df, interest_df, dim_id, dim_interest, interest_key):
    fact_df = dim_df.assign(**{dim_interest: dim_df[dim_interest].str.split(',')}).explode(dim_interest)
    fact_df[dim_interest] = fact_df[dim_interest].str.strip()
    fact_df = fact_df[[dim_id,dim_interest]].merge(interest_df, left_on=dim_interest, right_on=interest_key)
    fact_df = fact_df.drop([dim_interest, interest_key], axis=1)
    return fact_df

In [17]:
user_interest_test = create_interests_fact_table(ads, interests, 'ad_id','target_interests', 'interest')
user_interest_test

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [18]:
user_interest = (users.assign(interest=users['interests'].str.split(',')).explode('interest'))
user_interest['interest'] = user_interest['interest'].str.strip()
user_interest = user_interest[['user_id', 'interest']]
user_interest = user_interest.merge(interests, on='interest')
user_interest.drop('interest',axis=1,  inplace=True)
user_interest

,user_id,interest_id
0,a2474,6
1,a2474,8
2,14100000,7
3,14100000,6
4,14100000,3
...,...,...
19929,68b82,10
19930,39f39,8
19931,0b8e7,11
19932,0b8e7,5
19933,99e3f,6

In [19]:
ad_interest = (ads.assign(target_interests=ads['target_interests'].str.split(',')).explode('target_interests'))

ad_interest['target_interests'] = ad_interest['target_interests'].str.strip()

ad_interest = ad_interest[['ad_id', 'target_interests']]
ad_interest = ad_interest.merge(interests, left_on='target_interests', right_on='interest')
ad_interest.drop(['target_interests','interest'],axis=1,  inplace=True)
ad_interest

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [20]:
ad_interest = (ads.assign(target_interests=ads['target_interests'].str.split(',')).explode('target_interests'))

ad_interest['target_interests'] = ad_interest['target_interests'].str.strip()

ad_interest = ad_interest[['ad_id', 'target_interests']]
ad_interest

,ad_id,target_interests
0,1,art
0,1,technology
1,2,travel
1,2,photography
2,3,technology
...,...,...
197,198,fitness
197,198,lifestyle
198,199,art
198,199,news
199,200,photography

In [21]:
ad_interest = ad_interest.merge(interests, left_on='target_interests', right_on='interest')
ad_interest.drop(['target_interests','interest'],axis=1,  inplace=True)
ad_interest

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [22]:
pairs = [
    # fashion
    ("fashion", "lifestyle"),
    ("fashion", "art"),

    # news
    ("news", "finance"),
    ("news", "technology"),
    ("news", "sports"),

    # health
    ("health", "sports"),
    ("health", "fitness"),
    ("health", "food"),
    ("health", "lifestyle"),

    # lifestyle
    ("lifestyle", "health"),
    ("lifestyle", "fitness"),
    ("lifestyle", "fashion"),
    ("lifestyle", "travel"),

    # fitness
    ("fitness", "health"),
    ("fitness", "sports"),
    ("fitness", "food"),
    ("fitness", "lifestyle"),

    # technology
    ("technology", "gaming"),
    ("technology", "finance"),
    ("technology", "news"),
    ("technology", "photography"),

    # art
    ("art", "fashion"),
    ("art", "photography"),

    # travel
    ("travel", "photography"),
    ("travel", "lifestyle"),

    # food
    ("food", "lifestyle"),
    ("food", "health"),
    ("food", "fitness"),

    # sports
    ("sports", "fitness"),
    ("sports", "health"),
    ("sports", "news"),
    ("sports", "gaming"),

    # finance
    ("finance", "technology"),
    ("finance", "news"),

    # photography
    ("photography", "travel"),
    ("photography", "art"),
    ("photography", "technology"),

    # gaming
    ("gaming", "technology"),
    ("gaming", "sports"),

]
sub_interests = pd.DataFrame(pairs, columns=["interest", "related_interest"])

sub_interests = (sub_interests.merge(interests, on="interest")
    .rename(columns={"interest_id": "interest_id"}).merge(interests,
        left_on="related_interest", right_on="interest", suffixes=("", "_related"))
    [["interest_id", "interest_id_related"]]
)
sub_interests.sort_values("interest_id", inplace=True)
sub_interests

,interest_id,interest_id_related
24,1,3
23,1,9
2,2,10
3,2,12
4,2,4
9,3,8
10,3,6
11,3,5
12,3,1
30,4,2
29,4,8
28,4,6
31,4,13
0,5,3
1,5,11
16,6,3
14,6,4
13,6,8
15,6,7
27,7,6
26,7,8
25,7,3
5,8,4
6,8,6
7,8,7
8,8,3
34,9,1
35,9,11
36,9,12
33,10,2
32,10,12
21,11,5
22,11,9
19,12,2
18,12,10
17,12,13
20,12,9
37,13,12
38,13,4

In [23]:
users.drop('interests', axis=1, inplace=True)
ads.drop('target_interests', axis=1, inplace=True)
campaigns = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='ad_events')

In [17]:

tables = [users, campaigns, ads, interests, ad_events, user_interest, ad_interest, sub_interests]
sheet_names = ['users', 'campaigns', 'ads', 'interests', 'ad_events', 'user_interest',
               'ad_interest', 'sub_interests']
path = 'Social_Media_Campaign_Analysis.xlsx'
er =pd.ExcelWriter(path)
for i in range(len(tables)):
    tables[i].to_excel(er, sheet_name=sheet_names[i], index = False)
er.close()

# Data Cleaning

Uplode Data

In [22]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='users')
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ads')
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_events')
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='interests')
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='user_interest')
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_interest')
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='sub_interests')

### step 1
Remove duplicate entries for the same user ID from the users table.

In [23]:
duplicates = users['user_id'].duplicated(keep=False)
duplicate_user_ids = users.loc[duplicates,'user_id'].unique()
users_clean = users.loc[~users['user_id'].isin(duplicate_user_ids)]
users_clean

,user_id,user_gender,user_age,country,location
0,a2474,Female,24,United Kingdom,New Mariomouth
1,14100000,Male,21,Germany,Danielsfort
2,34db0,Male,27,Australia,Vincentchester
3,20d08,Female,28,India,Lisaport
4,9e830,Male,28,United States,Brownmouth
...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside
9996,68b82,Male,24,Mexico,Brownland
9997,39f39,Male,29,United States,Watersburgh
9998,0b8e7,Male,31,United Kingdom,South Kenneth
9999,99e3f,Male,37,Canada,New Courtneyview

In [24]:
removed = users.shape[0] -  users_clean.shape[0]
print(f'{removed} records were removed, {removed*100/users.shape[0]}% from the data')

107 records were removed, 1.07% from the data

### step 2
Remove duplicate entries for the same user ID from the ad_events table.

In [25]:
ad_events_clean = ad_events.loc[~ad_events['user_id'].isin(duplicate_user_ids)]
ad_events_clean

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [26]:
removed1 = ad_events.shape[0] -  ad_events_clean.shape[0]
print(f'{removed1} records were removed, {removed1*100/ad_events.shape[0]}% from the data')

4244 records were removed, 1.061% from the data

### step 3
Remove duplicate entries for the same user ID from the `users_interests` table.

In [27]:
user_interest_clean = user_interest.loc[~user_interest['user_id'].isin(duplicate_user_ids)]
user_interest_clean

,user_id,interest_id
0,a2474,12
1,a2474,6
2,14100000,7
3,14100000,12
4,14100000,4
...,...,...
19929,68b82,8
19930,39f39,6
19931,0b8e7,9
19932,0b8e7,1
19933,99e3f,12

In [29]:
removed2 = user_interest.shape[0] -  user_interest_clean.shape[0]
print(f'{removed2} records were removed, {round(removed2*100/user_interest.size,2)}% from the data')

213 records were removed, 0.53% from the data

### step 4
Remove records from the `ad_events` table with an event time earlier than the campaign start.

In [30]:
temp = ad_events_clean.merge(ads, on='ad_id')
temp = temp.merge(campaigns, on='campaign_id')
to_remove = temp.loc[temp['timestamp'] < temp['start_date']]['event_id']
ad_events_clean1 = ad_events_clean.loc[~ad_events_clean['event_id'].isin(to_remove)]
ad_events_clean1

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [31]:
removed3 = ad_events_clean.shape[0] -  ad_events_clean1.shape[0] 
print(f'{removed3} records were removed, {removed3*100/ad_events.shape[0]}% from the data')

2820 records were removed, 0.705% from the data

In [32]:
tables = [users_clean, campaigns, ads, interests, ad_events_clean1, user_interest_clean, ad_interest, sub_interests]
sheet_names = ['users', 'campaigns', 'ads', 'interests', 'ad_events', 'user_interest',
               'ad_interest', 'sub_interests']
path = 'Social_Media_Campaign_Analysis_Clean.xlsx'
er =pd.ExcelWriter(path)
for i in range(len(tables)):
    tables[i].to_excel(er, sheet_name=sheet_names[i], index = False)
er.close()

# Feature Engineering

Uplode Data

In [8]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='users')
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ads')
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ad_events')
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='interests')
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='user_interest')
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ad_interest')
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='sub_interests')

Splitting Age Ranges in the Ads Table

In [9]:
def extract_age(col_values, min_a, max_a):
    min_age_col,max_age_col = [], []

    for i in col_values:
        if i == 'All':
            min_age_col.append(min_a)
            max_age_col.append(max_a)
        else:
            min_age_col.append(int(i[:2]))
            max_age_col.append(int(i[-2:]))
    return min_age_col, max_age_col

min_age, max_age = min(users['user_age']), max(users['user_age'])
min_age_col, max_age_col = extract_age(ads['target_age_group'].values, min_age, max_age)
ads['min_age'] = min_age_col
ads['max_age'] = max_age_col
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,min_age,max_age
0,1,28,Facebook,Video,Female,35-44,35,44
1,2,33,Facebook,Stories,All,25-34,25,34
2,3,20,Instagram,Carousel,All,25-34,25,34
3,4,28,Facebook,Stories,Female,25-34,25,34
4,5,24,Instagram,Image,Female,25-34,25,34
...,...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,35,44
196,197,9,Facebook,Stories,All,All,16,65
197,198,34,Facebook,Video,All,35-44,35,44
198,199,15,Instagram,Video,Male,25-34,25,34
199,200,44,Instagram,Carousel,Male,18-24,18,24

Categorizing Ads and Users into Age Groups

In [10]:
label_dict = {'All':'All', '18-24':'Young', '25-34':'Young Adults', '35-44':'Adults'}
ads['age_group_label'] = ads['target_age_group'].map(label_dict)
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,min_age,max_age,age_group_label
0,1,28,Facebook,Video,Female,35-44,35,44,Adults
1,2,33,Facebook,Stories,All,25-34,25,34,Young Adults
2,3,20,Instagram,Carousel,All,25-34,25,34,Young Adults
3,4,28,Facebook,Stories,Female,25-34,25,34,Young Adults
4,5,24,Instagram,Image,Female,25-34,25,34,Young Adults
...,...,...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,35,44,Adults
196,197,9,Facebook,Stories,All,All,16,65,All
197,198,34,Facebook,Video,All,35-44,35,44,Adults
198,199,15,Instagram,Video,Male,25-34,25,34,Young Adults
199,200,44,Instagram,Carousel,Male,18-24,18,24,Young

Categorizing Users into Age Groups

In [13]:
bins = [16, 25, 35, 45, 66]
labels = ['Young', 'Young Adults', 'Adults', 'Elderly']
users['age_label'] = pd.cut(users['user_age'],bins=bins,labels=labels,right=False,include_lowest=True)
users['age_range'] = pd.cut(users['user_age'],bins=bins,right=False,include_lowest=True).apply(lambda x: f"{int(x.left)}-{int(x.right)-1}")
users

,user_id,user_gender,user_age,country,location,age_label,age_range
0,a2474,Female,24,United Kingdom,New Mariomouth,Young,16-24
1,14100000,Male,21,Germany,Danielsfort,Young,16-24
2,34db0,Male,27,Australia,Vincentchester,Young Adults,25-34
3,20d08,Female,28,India,Lisaport,Young Adults,25-34
4,9e830,Male,28,United States,Brownmouth,Young Adults,25-34
...,...,...,...,...,...,...,...
9888,24364,Male,18,United States,Curtisside,Young,16-24
9889,68b82,Male,24,Mexico,Brownland,Young,16-24
9890,39f39,Male,29,United States,Watersburgh,Young Adults,25-34
9891,0b8e7,Male,31,United Kingdom,South Kenneth,Young Adults,25-34
9892,99e3f,Male,37,Canada,New Courtneyview,Adults,35-44

Calculating Campaign Duration

In [14]:
campaigns['Duration (Days)'] = (campaigns['end_date'] - campaigns['start_date']).dt.days
campaigns

,campaign_id,name,start_date,end_date,total_budget,Duration (Days)
0,1,Campaign_1_Launch,2025-03-25,2025-07-23,24021.32,120
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,79342.41,82
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,14343.25,56
3,4,Campaign_4_Summer,2025-04-04,2025-08-08,45326.60,126
4,5,Campaign_5_Launch,2025-05-11,2025-08-28,68376.69,109
5,6,Campaign_6_Winter,2025-04-21,2025-09-13,78607.49,145
6,7,Campaign_7_Winter,2025-03-25,2025-08-05,43744.59,133
7,8,Campaign_8_Q3,2025-02-25,2025-04-07,39953.19,41
8,9,Campaign_9_Launch,2025-03-25,2025-07-13,40094.07,110
9,10,Campaign_10_Winter,2025-03-17,2025-07-21,19669.27,126
10,11,Campaign_11_Q3,2025-04-24,2025-07-02,79067.91,69
11,12,Campaign_12_Q3,2025-03-08,2025-06-01,30525.65,85
12,13,Campaign_13_Winter,2025-04-19,2025-07-01,21855.42,73
13,14,Campaign_14_Summer,2025-04-15,2025-06-04,39849.94,50
14,15,Campaign_15_Launch,2025-03-21,2025-06-11,85407.23,82
15,16,Campaign_16_Winter,2025-03-07,2025-06-04,71521.88,89
16,17,Campaign_17_Launch,2025-04-22,2025-07-18,86675.92,87
17,18,Campaign_18_Q3,2025-04-19,2025-06-15,48832.61,57
18,19,Campaign_19_Winter,2025-03-06,2025-05-15,33182.45,70
19,20,Campaign_20_Winter,2025-02-17,2025-05-18,98904.66,90
20,21,Campaign_21_Winter,2025-04-19,2025-06-22,37290.81,64
21,22,Campaign_22_Q3,2025-03-17,2025-04-22,35743.40,36
22,23,Campaign_23_Winter,2025-05-10,2025-10-02,26001.67,145
23,24,Campaign_24_Summer,2025-03-30,2025-05-23,56692.87,54
24,25,Campaign_25_Winter,2025-04-07,2025-09-04,52725.49,150
25,26,Campaign_26_Winter,2025-04-01,2025-06-17,44538.87,77
26,27,Campaign_27_Q3,2025-02-13,2025-04-02,12986.30,48
27,28,Campaign_28_Winter,2025-03-09,2025-06-30,32844.79,113
28,29,Campaign_29_Winter,2025-05-16,2025-10-06,19773.66,143
29,30,Campaign_30_Winter,2025-02-25,2025-05-10,73911.29,74
30,31,Campaign_31_Summer,2025-03-27,2025-07-22,72208.34,117
31,32,Campaign_32_Summer,2025-05-02,2025-06-14,81744.53,43
32,33,Campaign_33_Summer,2025-04-08,2025-07-04,59264.68,87
33,34,Campaign_34_Winter,2025-05-10,2025-09-08,26104.30,121
34,35,Campaign_35_Launch,2025-05-23,2025-10-12,71626.83,142
35,36,Campaign_36_Q3,2025-03-07,2025-05-13,58801.99,67
36,37,Campaign_37_Launch,2025-03-18,2025-08-01,46445.20,136
37,38,Campaign_38_Q3,2025-04-21,2025-05-27,71038.28,36
38,39,Campaign_39_Q3,2025-03-18,2025-07-27,55638.18,131
39,40,Campaign_40_Summer,2025-03-04,2025-04-20,53936.41,47
40,41,Campaign_41_Winter,2025-04-02,2025-06-12,85220.35,71
41,42,Campaign_42_Summer,2025-04-08,2025-07-25,7918.04,108
42,43,Campaign_43_Winter,2025-04-23,2025-06-12,81350.30,50
43,44,Campaign_44_Q3,2025-05-14,2025-09-22,15914.87,131
44,45,Campaign_45_Summer,2025-03-26,2025-08-05,53303.55,132
45,46,Campaign_46_Winter,2025-03-10,2025-08-07,94023.76,150
46,47,Campaign_47_Launch,2025-04-17,2025-09-03,69493.36,139
47,48,Campaign_48_Winter,2025-04-08,2025-06-01,13842.07,54
48,49,Campaign_49_Winter,2025-02-21,2025-05-17,28962.34,85
49,50,Campaign_50_Summer,2025-05-02,2025-08-03,47274.70,93

Extracting Date and Time Features

In [15]:
ad_events['Day_Of_Week'] = ad_events['timestamp'].dt.day_name()
ad_events['Is_weekend'] = ad_events['timestamp'].dt.dayofweek >= 4
ad_events['Hour'] = ad_events['timestamp'].dt.hour
ad_events

,event_id,ad_id,user_id,timestamp,event_type,Day_Of_Week,Is_weekend,Hour
0,1,197,2359b,2025-07-26 00:19:56,Like,Saturday,True,0
1,2,51,f9c67,2025-06-15 08:28:07,Share,Sunday,True,8
2,3,46,5b868,2025-06-27 00:40:02,Impression,Friday,True,0
3,4,166,3d440,2025-06-05 19:20:45,Impression,Thursday,False,19
4,5,52,68f1a,2025-07-22 08:30:29,Impression,Tuesday,False,8
...,...,...,...,...,...,...,...,...
392931,399996,132,3cb8c,2025-08-01 22:36:54,Impression,Friday,True,22
392932,399997,200,fe0e3,2025-05-31 14:53:18,Impression,Saturday,True,14
392933,399998,2,a08c1,2025-07-27 13:39:51,Click,Sunday,True,13
392934,399999,109,4f0cf,2025-05-16 02:38:23,Impression,Friday,True,2
392935,400000,63,2c11d,2025-06-15 12:06:28,Impression,Sunday,True,12

In [16]:
from datetime import time

def get_day_part_from_time(t, day_part_dict):
    h = t
    for (start, end), label in day_part_dict.items():
        if start <= end:
            if start <= h <= end:
                return label
        else:
            if h >= start or h <= end:
                return label
    return None

In [17]:
day_part = {(6,11):'morning',(12,16):'noon', (17,22):'evening',(23,5):'night'}
ad_events['day_part'] = ad_events['Hour'].apply(
    lambda h: get_day_part_from_time(h, day_part)
)
ad_events

,event_id,ad_id,user_id,timestamp,event_type,Day_Of_Week,Is_weekend,Hour,day_part
0,1,197,2359b,2025-07-26 00:19:56,Like,Saturday,True,0,night
1,2,51,f9c67,2025-06-15 08:28:07,Share,Sunday,True,8,morning
2,3,46,5b868,2025-06-27 00:40:02,Impression,Friday,True,0,night
3,4,166,3d440,2025-06-05 19:20:45,Impression,Thursday,False,19,evening
4,5,52,68f1a,2025-07-22 08:30:29,Impression,Tuesday,False,8,morning
...,...,...,...,...,...,...,...,...,...
392931,399996,132,3cb8c,2025-08-01 22:36:54,Impression,Friday,True,22,evening
392932,399997,200,fe0e3,2025-05-31 14:53:18,Impression,Saturday,True,14,noon
392933,399998,2,a08c1,2025-07-27 13:39:51,Click,Sunday,True,13,noon
392934,399999,109,4f0cf,2025-05-16 02:38:23,Impression,Friday,True,2,night
392935,400000,63,2c11d,2025-06-15 12:06:28,Impression,Sunday,True,12,noon

In [18]:
tables = [users, campaigns, ads, interests, ad_events, user_interest, ad_interest, sub_interests]
sheet_names = ['users', 'campaigns', 'ads', 'interests', 'ad_events', 'user_interest',
               'ad_interest', 'sub_interests']
path = 'Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx'
er =pd.ExcelWriter(path)
for i in range(len(tables)):
    tables[i].to_excel(er, sheet_name=sheet_names[i], index = False)
er.close()

# KPI Calculations

In [2]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='users')
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='ads')
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='ad_events')
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='interests')
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='user_interest')
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='ad_interest')
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean&feature_engineered.xlsx', sheet_name='sub_interests')

#### Total Interactions

In [17]:
total_interactions = ad_events.shape[0]
print("Total events: " + str(total_interactions))
total_users = users.shape[0]
print("Total users: " + str(total_users))
total_ads = ads.shape[0]
print("Total ads: " + str(total_ads))
total_campaigns = campaigns.shape[0]
print("Total campaigns: " + str(total_campaigns))

Total events: 392936
Total users: 9893
Total ads: 200
Total campaigns: 50

#### Interactions by Campaign

In [7]:
interactions_by_campaign = (ad_events.merge(ads[['ad_id', 'campaign_id']], on='ad_id')
    .groupby('campaign_id').size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_campaign

,campaign_id,interaction_count
18,20,15871
40,42,15837
22,24,15831
15,17,15798
36,38,15710
31,33,14016
27,29,12453
12,13,12046
8,9,12001
44,47,11963
3,4,11882
35,37,11855
32,34,11571
23,25,10080
20,22,10013
7,8,9932
43,46,9907
14,15,9801
30,32,8035
28,30,7921
38,40,7867
19,21,7844
2,3,7812
9,10,7739
41,44,7324
1,2,6081
37,39,6021
39,41,5988
26,28,5970
5,6,5954
24,26,5945
10,11,5939
29,31,5871
6,7,5866
16,18,5864
0,1,5860
4,5,5770
21,23,5689
11,12,4002
34,36,3978
17,19,3975
46,49,3972
45,48,3912
25,27,3899
42,45,3842
13,14,3840
47,50,1981
33,35,1608

#### Interactions by Ad

In [8]:
interactions_by_ad = (ad_events.groupby('ad_id').size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_ad

,ad_id,interaction_count
191,192,2091
69,70,2089
101,102,2072
100,101,2070
65,66,2070
...,...,...
162,163,1778
53,54,1767
82,83,1760
80,81,1727
42,43,1608

#### Interactions by Platform

In [19]:
interactions_by_platform = (ad_events.merge(ads[['ad_id', 'ad_platform']], on='ad_id')
    .groupby('ad_platform').size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_platform

,ad_platform,interaction_count
0,Facebook,250274
1,Instagram,142662

#### Interactions by type

In [10]:
interactions_by_type = (ad_events.merge(ads[['ad_id', 'ad_platform', 'ad_type']], on='ad_id')
    .groupby(['ad_platform', 'ad_type']).size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_type

,ad_platform,ad_type,interaction_count
2,Facebook,Stories,83378
1,Facebook,Image,59039
0,Facebook,Carousel,55311
3,Facebook,Video,52546
4,Instagram,Carousel,44688
5,Instagram,Image,43032
6,Instagram,Stories,42977
7,Instagram,Video,11965

#### Interactions by event type

In [12]:
interactions_by_event = (ad_events.merge(ads[['ad_id', 'ad_platform']], on='ad_id')
    .groupby(['ad_platform', 'event_type']).size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_event

,ad_platform,event_type,interaction_count
2,Facebook,Impression,212734
8,Instagram,Impression,121107
0,Facebook,Click,24993
6,Instagram,Click,14352
3,Facebook,Like,7392
9,Instagram,Like,4393
1,Facebook,Comment,2597
7,Instagram,Comment,1456
4,Facebook,Purchase,1302
5,Facebook,Share,1256
10,Instagram,Purchase,687
11,Instagram,Share,667

#### Campaign Cost vs User Events

In [3]:
campaign_performance = (ad_events.merge(ads[['ad_id', 'campaign_id']], on='ad_id')
    .merge(campaigns[['campaign_id', 'total_budget']], on='campaign_id')
    .groupby(['campaign_id', 'total_budget']).size()
    .reset_index(name='interaction_count').sort_values('total_budget', ascending=False)
)
campaign_performance

,campaign_id,total_budget,interaction_count
18,20,98904.66,15871
43,46,94023.76,9907
15,17,86675.92,15798
14,15,85407.23,9801
39,41,85220.35,5988
30,32,81744.53,8035
1,2,79342.41,6081
10,11,79067.91,5939
5,6,78607.49,5954
28,30,73911.29,7921
29,31,72208.34,5871
33,35,71626.83,1608
36,38,71038.28,15710
44,47,69493.36,11963
4,5,68376.69,5770
31,33,59264.68,14016
34,36,58801.99,3978
22,24,56692.87,15831
37,39,55638.18,6021
38,40,53936.41,7867
42,45,53303.55,3842
23,25,52725.49,10080
16,18,48832.61,5864
47,50,47274.70,1981
35,37,46445.20,11855
3,4,45326.60,11882
24,26,44538.87,5945
6,7,43744.59,5866
8,9,40094.07,12001
7,8,39953.19,9932
13,14,39849.94,3840
19,21,37290.81,7844
20,22,35743.40,10013
17,19,33182.45,3975
26,28,32844.79,5970
11,12,30525.65,4002
46,49,28962.34,3972
32,34,26104.30,11571
21,23,26001.67,5689
0,1,24021.32,5860
12,13,21855.42,12046
27,29,19773.66,12453
9,10,19669.27,7739
41,44,15914.87,7324
2,3,14343.25,7812
45,48,13842.07,3912
25,27,12986.30,3899
40,42,7918.04,15837

#### Interactions by Age Group (Users)

In [29]:
interactions_by_age_group = (ad_events.merge(users[['user_id', 'age_label', 'age_range']], on='user_id')
    .groupby(['age_label', 'age_range']).size().reset_index(name='interaction_count')
    .sort_values('age_range', ascending=True)
)
interactions_by_age_group

,age_label,age_range,interaction_count
2,Young,16-24,157534
3,Young Adults,25-34,162463
0,Adults,35-44,56802
1,Elderly,45-65,16137

#### Targeting Match – User Age vs Ad Age

In [20]:
targeting_match = (ad_events.merge(users[['user_id', 'age_label']], on='user_id')
    .merge(ads[['ad_id', 'age_group_label']], on='ad_id').groupby(['age_group_label', 'age_label'])
    .size().reset_index(name='interaction_count')
)
total_per_ad_age = targeting_match.groupby('age_group_label')['interaction_count'].transform('sum')
targeting_match['interaction_ratio'] = ((targeting_match['interaction_count'] / total_per_ad_age) * 100).round(2)
targeting_match.rename(columns={'age_label': 'user_age', 'age_group_label': 'ad_age'})

,ad_age,user_age,interaction_count,interaction_ratio
0,Adults,Adults,15328,14.47
1,Adults,Elderly,4357,4.11
2,Adults,Young,42416,40.04
3,Adults,Young Adults,43829,41.38
4,All,Adults,13090,14.47
5,All,Elderly,3655,4.04
6,All,Young,36360,40.20
7,All,Young Adults,37347,41.29
8,Young,Adults,15387,14.46
9,Young,Elderly,4471,4.20
10,Young,Young,42775,40.20
11,Young,Young Adults,43781,41.14
12,Young Adults,Adults,12997,14.42
13,Young Adults,Elderly,3654,4.05
14,Young Adults,Young,35983,39.92
15,Young Adults,Young Adults,37506,41.61

#### Interactions by Gender

In [26]:
interactions_by_gender = (ad_events.merge(users[['user_id', 'user_gender']], on='user_id')
    .groupby('user_gender').size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_gender

,user_gender,interaction_count
1,Male,217759
0,Female,135374
2,Other,39803

#### Targeting Match – User Gender vs Ad Gender Target

In [21]:
targeting_match1 = (ad_events.merge(users[['user_id', 'user_gender']], on='user_id')
    .merge(ads[['ad_id', 'target_gender']], on='ad_id').groupby(['target_gender', 'user_gender'])
    .size().reset_index(name='interaction_count')
)
total_per_ad_gender = targeting_match1.groupby('target_gender')['interaction_count'].transform('sum')
targeting_match1['interaction_ratio'] = ((targeting_match1['interaction_count'] / total_per_ad_gender) * 100).round(2)
targeting_match1

,target_gender,user_gender,interaction_count,interaction_ratio
0,All,Female,48007,34.51
1,All,Male,77022,55.37
2,All,Other,14064,10.11
3,Female,Female,56229,34.45
4,Female,Male,90505,55.45
5,Female,Other,16481,10.10
6,Male,Female,31138,34.36
7,Male,Male,50232,55.43
8,Male,Other,9258,10.22

#### Interactions by Interest

In [25]:
interactions_by_interest = (ad_events.merge(ad_interest, on='ad_id')
    .merge(interests, on='interest_id').groupby('interest')
    .size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_interest

,interest,interaction_count
3,fitness,61914
11,technology,61311
12,travel,61101
0,art,60980
5,gaming,60734
7,lifestyle,60692
1,fashion,60257
10,sports,59889
6,health,59868
4,food,59282
8,news,59177
2,finance,58911
9,photography,58539

#### Ad Interest Match: Exact, Family, No Match

In [27]:

temp = ad_events.merge(users[['user_id']], on='user_id')
temp = temp.merge(ads[['ad_id']], on='ad_id')
temp = temp.merge(user_interest, on='user_id')
temp = temp.merge(ad_interest, on='ad_id', suffixes=('_user', '_ad')) 
temp = temp.merge(sub_interests, left_on='interest_id_user', right_on='interest_id_related', how='left')
temp['exact_match'] = temp['interest_id_user'] == temp['interest_id_ad']
temp['family_match'] = (~temp['exact_match']) & (temp['interest_id_ad'].notnull()) & (temp['interest_id_related'].notnull())
temp['no_match'] = (~temp['exact_match']) & (~temp['family_match'])

interest_match_summary = temp.groupby('ad_id').agg(
    exact_match_count=('exact_match', 'sum'),
    family_match_count=('family_match', 'sum'),
    no_match_count=('no_match', 'sum')
).reset_index()

interest_match_summary

,ad_id,exact_match_count,family_match_count,no_match_count
0,1,1922,22482,0
1,2,1433,22635,0
2,3,1288,10575,0
3,4,903,11290,0
4,5,981,11093,0
...,...,...,...,...
195,196,1858,21752,0
196,197,2162,21564,0
197,198,2771,19827,0
198,199,1526,21744,0
199,200,846,9993,0

#### User Interest Distribution by Age

In [6]:
age_interest_count = (user_interest.merge(users[['user_id', 'age_label']], on='user_id')
    .merge(interests[['interest_id', 'interest']], on='interest_id')
    .groupby(['interest', 'age_label'])['user_id'].nunique()
    .reset_index(name='unique_user_count')
)
age_interest_count

,interest,age_label,unique_user_count
0,art,Adults,238
1,art,Elderly,60
2,art,Young,606
3,art,Young Adults,629
4,fashion,Adults,217
5,fashion,Elderly,63
6,fashion,Young,613
7,fashion,Young Adults,631
8,finance,Adults,211
9,finance,Elderly,48
10,finance,Young,610
11,finance,Young Adults,610
12,fitness,Adults,236
13,fitness,Elderly,76
14,fitness,Young,649
15,fitness,Young Adults,605
16,food,Adults,243
17,food,Elderly,61
18,food,Young,589
19,food,Young Adults,601
20,gaming,Adults,226
21,gaming,Elderly,57
22,gaming,Young,611
23,gaming,Young Adults,637
24,health,Adults,201
25,health,Elderly,67
26,health,Young,573
27,health,Young Adults,673
28,lifestyle,Adults,207
29,lifestyle,Elderly,61
30,lifestyle,Young,633
31,lifestyle,Young Adults,627
32,news,Adults,221
33,news,Elderly,55
34,news,Young,605
35,news,Young Adults,614
36,photography,Adults,205
37,photography,Elderly,74
38,photography,Young,561
39,photography,Young Adults,629
40,sports,Adults,219
41,sports,Elderly,49
42,sports,Young,634
43,sports,Young Adults,605
44,technology,Adults,188
45,technology,Elderly,64
46,technology,Young,644
47,technology,Young Adults,656
48,travel,Adults,240
49,travel,Elderly,70
50,travel,Young,626
51,travel,Young Adults,593

#### User Interest Distribution by Gender

In [7]:
age_interest_count1 = (user_interest.merge(users[['user_id', 'user_gender']], on='user_id')
    .merge(interests[['interest_id', 'interest']], on='interest_id')
    .groupby(['interest', 'user_gender'])['user_id'].nunique()
    .reset_index(name='unique_user_count')
)
age_interest_count1

,interest,user_gender,unique_user_count
0,art,Female,511
1,art,Male,881
2,art,Other,141
3,fashion,Female,512
4,fashion,Male,843
5,fashion,Other,169
6,finance,Female,502
7,finance,Male,822
8,finance,Other,155
9,fitness,Female,553
10,fitness,Male,846
11,fitness,Other,167
12,food,Female,541
13,food,Male,807
14,food,Other,146
15,gaming,Female,543
16,gaming,Male,837
17,gaming,Other,151
18,health,Female,517
19,health,Male,838
20,health,Other,159
21,lifestyle,Female,522
22,lifestyle,Male,845
23,lifestyle,Other,161
24,news,Female,491
25,news,Male,849
26,news,Other,155
27,photography,Female,524
28,photography,Male,813
29,photography,Other,132
30,sports,Female,511
31,sports,Male,839
32,sports,Other,157
33,technology,Female,533
34,technology,Male,866
35,technology,Other,153
36,travel,Female,550
37,travel,Male,827
38,travel,Other,152

#### Event count per interest and platform

In [14]:
event_order = {'Impression': 1, 'Like': 2, 'Comment': 3, 'Share': 4, 'Click': 5, 'Purchase': 6}
interest_platform_events = (ad_events.merge(ads[['ad_id', 'ad_platform']], on='ad_id')
    .merge(ad_interest, on='ad_id').merge(interests[['interest_id', 'interest']], on='interest_id')
    .groupby(['interest', 'ad_platform', 'event_type'])['event_id']
    .count().reset_index(name='event_count'))

interest_platform_events = interest_platform_events.sort_values(
    by=['interest', 'ad_platform', 'event_type'],
    key=lambda col: col.map(event_order) if col.name == 'event_type' else col)

interest_platform_events

,interest,ad_platform,event_type,event_count
2,art,Facebook,Impression,16713
3,art,Facebook,Like,604
1,art,Facebook,Comment,211
5,art,Facebook,Share,103
0,art,Facebook,Click,1966
...,...,...,...,...
153,travel,Instagram,Like,582
151,travel,Instagram,Comment,194
155,travel,Instagram,Share,96
150,travel,Instagram,Click,1961
154,travel,Instagram,Purchase,83

#### Time-Based Engagement

In [24]:
interactions_by_day = (ad_events.groupby('Day_Of_Week').size()
    .reset_index(name='interaction_count')
)
interactions_by_day

,Day_Of_Week,interaction_count
0,Friday,56253
1,Monday,56388
2,Saturday,56079
3,Sunday,56078
4,Thursday,55830
5,Tuesday,56205
6,Wednesday,56103

In [5]:
interactions_by_hour = (ad_events.groupby('Hour').size()
    .reset_index(name='interaction_count')
)
interactions_by_hour

,Hour,interaction_count
0,0,16335
1,1,16358
2,2,16592
3,3,16236
4,4,16311
5,5,16354
6,6,16295
7,7,16180
8,8,16627
9,9,16251
10,10,16328
11,11,16488
12,12,16487
13,13,16494
14,14,16403
15,15,16257
16,16,16340
17,17,16363
18,18,16402
19,19,16388
20,20,16497
21,21,16379
22,22,16284
23,23,16287

In [6]:
interactions_by_day_part = (ad_events.groupby('day_part').size()
    .reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_day_part

,day_part,interaction_count
2,night,114473
0,evening,98313
1,morning,98169
3,noon,81981

In [7]:
interactions_weekend = (ad_events.groupby(['Day_Of_Week', 'Is_weekend'])
    .size().reset_index(name='interaction_count')
)
avg_interactions = (interactions_weekend.groupby('Is_weekend')['interaction_count']
    .mean().round(2).reset_index(name='avg_interactions')
)
avg_interactions

,Is_weekend,avg_interactions
0,False,56131.50
1,True,56136.67

#### Campaign Engagement Relative to Campaign Duration

In [8]:
temp = ad_events.merge(ads[['ad_id', 'campaign_id']], on='ad_id')
temp = temp.merge(campaigns[['campaign_id', 'start_date', 'end_date', 'Duration (Days)']], on='campaign_id')

temp['during_campaign'] = (temp['timestamp'] >= temp['start_date']) & (temp['timestamp'] <= temp['end_date'])
temp['after_campaign'] = temp['timestamp'] > temp['end_date']

campaign_event_summary = temp.groupby(['campaign_id', 'Duration (Days)']).agg(events_during_campaign=('during_campaign', 'sum'),
    events_after_campaign=('after_campaign', 'sum')
).reset_index()
campaign_event_summary

,campaign_id,Duration (Days),events_during_campaign,events_after_campaign
0,1,120,4942,918
1,2,82,4084,1997
2,3,56,4525,3287
3,4,126,11882,0
4,5,109,5770,0
5,6,145,5954,0
6,7,133,5771,95
7,8,41,0,9932
8,9,110,8769,3232
9,10,126,6380,1359
10,11,69,3610,2329
11,12,85,1076,2926
12,13,73,7218,4828
13,14,50,1129,2711
14,15,82,3684,6117
15,17,87,12456,3342
16,18,57,2496,3368
17,19,70,318,3657
18,20,90,1937,13934
19,21,64,3985,3859
20,22,36,0,10013
21,23,145,5689,0
22,24,54,2599,13232
23,25,150,10080,0
24,26,77,2660,3285
25,27,48,0,3899
26,28,113,3549,2421
27,29,143,12453,0
28,30,74,215,7706
29,31,117,4852,1019
30,32,43,3303,4732
31,33,87,8828,5188
32,34,121,11571,0
33,35,142,1608,0
34,36,67,216,3762
35,37,136,11127,728
36,38,36,3360,12350
37,39,131,5312,709
38,40,47,0,7867
39,41,71,2348,3640
40,42,108,13678,2159
41,44,131,7324,0
42,45,132,3775,67
43,46,150,9907,0
44,47,139,11963,0
45,48,54,1041,2871
46,49,85,417,3555
47,50,93,1902,79

#### Interactions by Country

In [8]:
interactions_by_country = (ad_events.merge(users[['user_id', 'country']], on='user_id')
    .groupby('country').size().reset_index(name='interaction_count')
    .sort_values('interaction_count', ascending=False)
)
interactions_by_country

,country,interaction_count
9,United States,118467
8,United Kingdom,59321
2,Canada,39459
5,India,36941
4,Germany,32480
0,Australia,27900
1,Brazil,24008
7,Mexico,20128
6,Japan,19291
3,France,14941

#### Conversion Funnel: Impression → Click → Purchase

In [3]:
# Conversion funnel: Impression -> Click -> Purchase

event_counts = (
    ad_events['event_type']
    .value_counts()
    .reindex(['Impression', 'Click', 'Purchase'], fill_value=0)
)

impressions = event_counts['Impression']
clicks = event_counts['Click']
purchases = event_counts['Purchase']

conversion_funnel = pd.DataFrame({
    'metric': [
        'Total Impressions',
        'Clicks from Impressions',
        'Purchases from Clicks'
    ],
    'count': [
        impressions,
        clicks,
        purchases
    ],
    'percentage': [
        100,
        (clicks / impressions * 100) if impressions > 0 else 0,
        (purchases / clicks * 100) if clicks > 0 else 0
    ]
})

conversion_funnel['percentage'] = conversion_funnel['percentage'].round(2)

conversion_funnel

,metric,count,percentage
0,Total Impressions,333841,100.00
1,Clicks from Impressions,39345,11.79
2,Purchases from Clicks,1989,5.06

#### Average Events per User by Age Range and Gender

In [7]:

events_with_users = ad_events.merge(
    users[['user_id', 'age_range', 'user_gender']],
    on='user_id',
    how='left'
)

events_per_user = (
    events_with_users
    .groupby(['user_id', 'age_range', 'user_gender'])
    .size()
    .reset_index(name='events_count')
)

avg_events_by_age_gender = (
    events_per_user
    .groupby(['age_range', 'user_gender'])
    .agg(
        avg_events_per_user=('events_count', 'mean'),
        users_count=('user_id', 'count')
    )
    .reset_index()
    .round({'avg_events_per_user': 2})
)

avg_events_by_age_gender

,age_range,user_gender,avg_events_per_user,users_count
0,16-24,Female,39.59,1377
1,16-24,Male,39.65,2214
2,16-24,Other,39.54,385
3,25-34,Female,39.80,1397
4,25-34,Male,39.77,2255
5,25-34,Other,39.70,433
6,35-44,Female,39.17,499
7,35-44,Male,39.87,794
8,35-44,Other,39.72,141
9,45-65,Female,40.81,140
10,45-65,Male,40.54,213
11,45-65,Other,39.76,45