# Normalize Data

In [2]:
import pandas as pd
import numpy as np
!pip install xlrd
!pip install openpyxl

Requirement already satisfied: xlrd in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.0.2)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

Uplode user table

In [11]:
users = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='users')
users

,user_id,user_gender,user_age,country,location,interests
0,a2474,Female,24,United Kingdom,New Mariomouth,"fitness, health"
1,14100000,Male,21,Germany,Danielsfort,"food, fitness, lifestyle"
2,34db0,Male,27,Australia,Vincentchester,"fashion, news"
3,20d08,Female,28,India,Lisaport,"health, news, finance"
4,9e830,Male,28,United States,Brownmouth,"health, photography, lifestyle"
...,...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside,"travel, fashion, art"
9996,68b82,Male,24,Mexico,Brownland,finance
9997,39f39,Male,29,United States,Watersburgh,health
9998,0b8e7,Male,31,United Kingdom,South Kenneth,"art, fashion"
9999,99e3f,Male,37,Canada,New Courtneyview,fitness

Uplode Ads table

In [12]:
ads = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='ads')
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology
3,4,28,Facebook,Stories,Female,25-34,news
4,5,24,Instagram,Image,Female,25-34,news
...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,"gaming, sports"
196,197,9,Facebook,Stories,All,All,"lifestyle, gaming"
197,198,34,Facebook,Video,All,35-44,"fitness, lifestyle"
198,199,15,Instagram,Video,Male,25-34,"art, news"
199,200,44,Instagram,Carousel,Male,18-24,photography

In [14]:
def disttinct_intrests(interests):
    res = ", ".join(interests)
    return set(res.split(", "))

In [15]:
users_interests = disttinct_intrests(users['interests'])
ads_interests = disttinct_intrests(ads['target_interests'])
all_interests = users_interests | ads_interests

interests = pd.DataFrame({'interest_id': range(1, len(all_interests) + 1), 'interest': list(all_interests)})
interests

,interest_id,interest
0,1,travel
1,2,news
2,3,lifestyle
3,4,sports
4,5,fashion
5,6,fitness
6,7,food
7,8,health
8,9,photography
9,10,finance
10,11,art
11,12,technology
12,13,gaming

In [16]:
def create_interests_fact_table(dim_df, interest_df, dim_id, dim_interest, interest_key):
    fact_df = dim_df.assign(**{dim_interest: dim_df[dim_interest].str.split(',')}).explode(dim_interest)
    fact_df[dim_interest] = fact_df[dim_interest].str.strip()
    fact_df = fact_df[[dim_id,dim_interest]].merge(interest_df, left_on=dim_interest, right_on=interest_key)
    fact_df = fact_df.drop([dim_interest, interest_key], axis=1)
    return fact_df

In [17]:
user_interest_test = create_interests_fact_table(ads, interests, 'ad_id','target_interests', 'interest')
user_interest_test

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [18]:
user_interest = (users.assign(interest=users['interests'].str.split(',')).explode('interest'))
user_interest['interest'] = user_interest['interest'].str.strip()
user_interest = user_interest[['user_id', 'interest']]
user_interest = user_interest.merge(interests, on='interest')
user_interest.drop('interest',axis=1,  inplace=True)
user_interest

,user_id,interest_id
0,a2474,6
1,a2474,8
2,14100000,7
3,14100000,6
4,14100000,3
...,...,...
19929,68b82,10
19930,39f39,8
19931,0b8e7,11
19932,0b8e7,5
19933,99e3f,6

In [19]:
ad_interest = (ads.assign(target_interests=ads['target_interests'].str.split(',')).explode('target_interests'))

ad_interest['target_interests'] = ad_interest['target_interests'].str.strip()

ad_interest = ad_interest[['ad_id', 'target_interests']]
ad_interest = ad_interest.merge(interests, left_on='target_interests', right_on='interest')
ad_interest.drop(['target_interests','interest'],axis=1,  inplace=True)
ad_interest

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [20]:
ad_interest = (ads.assign(target_interests=ads['target_interests'].str.split(',')).explode('target_interests'))

ad_interest['target_interests'] = ad_interest['target_interests'].str.strip()

ad_interest = ad_interest[['ad_id', 'target_interests']]
ad_interest

,ad_id,target_interests
0,1,art
0,1,technology
1,2,travel
1,2,photography
2,3,technology
...,...,...
197,198,fitness
197,198,lifestyle
198,199,art
198,199,news
199,200,photography

In [21]:
ad_interest = ad_interest.merge(interests, left_on='target_interests', right_on='interest')
ad_interest.drop(['target_interests','interest'],axis=1,  inplace=True)
ad_interest

,ad_id,interest_id
0,1,11
1,1,12
2,2,1
3,2,9
4,3,12
...,...,...
295,198,6
296,198,3
297,199,11
298,199,2
299,200,9

In [22]:
pairs = [
    # fashion
    ("fashion", "lifestyle"),
    ("fashion", "art"),

    # news
    ("news", "finance"),
    ("news", "technology"),
    ("news", "sports"),

    # health
    ("health", "sports"),
    ("health", "fitness"),
    ("health", "food"),
    ("health", "lifestyle"),

    # lifestyle
    ("lifestyle", "health"),
    ("lifestyle", "fitness"),
    ("lifestyle", "fashion"),
    ("lifestyle", "travel"),

    # fitness
    ("fitness", "health"),
    ("fitness", "sports"),
    ("fitness", "food"),
    ("fitness", "lifestyle"),

    # technology
    ("technology", "gaming"),
    ("technology", "finance"),
    ("technology", "news"),
    ("technology", "photography"),

    # art
    ("art", "fashion"),
    ("art", "photography"),

    # travel
    ("travel", "photography"),
    ("travel", "lifestyle"),

    # food
    ("food", "lifestyle"),
    ("food", "health"),
    ("food", "fitness"),

    # sports
    ("sports", "fitness"),
    ("sports", "health"),
    ("sports", "news"),
    ("sports", "gaming"),

    # finance
    ("finance", "technology"),
    ("finance", "news"),

    # photography
    ("photography", "travel"),
    ("photography", "art"),
    ("photography", "technology"),

    # gaming
    ("gaming", "technology"),
    ("gaming", "sports"),

]
sub_interests = pd.DataFrame(pairs, columns=["interest", "related_interest"])

sub_interests = (sub_interests.merge(interests, on="interest")
    .rename(columns={"interest_id": "interest_id"}).merge(interests,
        left_on="related_interest", right_on="interest", suffixes=("", "_related"))
    [["interest_id", "interest_id_related"]]
)
sub_interests.sort_values("interest_id", inplace=True)
sub_interests

,interest_id,interest_id_related
24,1,3
23,1,9
2,2,10
3,2,12
4,2,4
9,3,8
10,3,6
11,3,5
12,3,1
30,4,2
29,4,8
28,4,6
31,4,13
0,5,3
1,5,11
16,6,3
14,6,4
13,6,8
15,6,7
27,7,6
26,7,8
25,7,3
5,8,4
6,8,6
7,8,7
8,8,3
34,9,1
35,9,11
36,9,12
33,10,2
32,10,12
21,11,5
22,11,9
19,12,2
18,12,10
17,12,13
20,12,9
37,13,12
38,13,4

In [23]:
users.drop('interests', axis=1, inplace=True)
ads.drop('target_interests', axis=1, inplace=True)
campaigns = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/social_media_campaign_analysis_sorce.xlsx', sheet_name='ad_events')

In [17]:

tables = [users, campaigns, ads, interests, ad_events, user_interest, ad_interest, sub_interests]
sheet_names = ['users', 'campaigns', 'ads', 'interests', 'ad_events', 'user_interest',
               'ad_interest', 'sub_interests']
path = 'Social_Media_Campaign_Analysis.xlsx'
er =pd.ExcelWriter(path)
for i in range(len(tables)):
    tables[i].to_excel(er, sheet_name=sheet_names[i], index = False)
er.close()

# Data Cleaning

Uplode Data

In [22]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='users')
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ads')
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_events')
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='interests')
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='user_interest')
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_interest')
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='sub_interests')

### step 1
Remove duplicate entries for the same user ID from the users table.

In [23]:
duplicates = users['user_id'].duplicated(keep=False)
duplicate_user_ids = users.loc[duplicates,'user_id'].unique()
users_clean = users.loc[~users['user_id'].isin(duplicate_user_ids)]
users_clean

,user_id,user_gender,user_age,country,location
0,a2474,Female,24,United Kingdom,New Mariomouth
1,14100000,Male,21,Germany,Danielsfort
2,34db0,Male,27,Australia,Vincentchester
3,20d08,Female,28,India,Lisaport
4,9e830,Male,28,United States,Brownmouth
...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside
9996,68b82,Male,24,Mexico,Brownland
9997,39f39,Male,29,United States,Watersburgh
9998,0b8e7,Male,31,United Kingdom,South Kenneth
9999,99e3f,Male,37,Canada,New Courtneyview

In [24]:
removed = users.shape[0] -  users_clean.shape[0]
print(f'{removed} records were removed, {removed*100/users.shape[0]}% from the data')

107 records were removed, 1.07% from the data

### step 2
Remove duplicate entries for the same user ID from the ad_events table.

In [25]:
ad_events_clean = ad_events.loc[~ad_events['user_id'].isin(duplicate_user_ids)]
ad_events_clean

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [26]:
removed1 = ad_events.shape[0] -  ad_events_clean.shape[0]
print(f'{removed1} records were removed, {removed1*100/ad_events.shape[0]}% from the data')

4244 records were removed, 1.061% from the data

### step 3
Remove duplicate entries for the same user ID from the `users_interests` table.

In [27]:
user_interest_clean = user_interest.loc[~user_interest['user_id'].isin(duplicate_user_ids)]
user_interest_clean

,user_id,interest_id
0,a2474,12
1,a2474,6
2,14100000,7
3,14100000,12
4,14100000,4
...,...,...
19929,68b82,8
19930,39f39,6
19931,0b8e7,9
19932,0b8e7,1
19933,99e3f,12

In [29]:
removed2 = user_interest.shape[0] -  user_interest_clean.shape[0]
print(f'{removed2} records were removed, {round(removed2*100/user_interest.size,2)}% from the data')

213 records were removed, 0.53% from the data

### step 4
Remove records from the `ad_events` table with an event time earlier than the campaign start.

In [30]:
temp = ad_events_clean.merge(ads, on='ad_id')
temp = temp.merge(campaigns, on='campaign_id')
to_remove = temp.loc[temp['timestamp'] < temp['start_date']]['event_id']
ad_events_clean1 = ad_events_clean.loc[~ad_events_clean['event_id'].isin(to_remove)]
ad_events_clean1

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [31]:
removed3 = ad_events_clean.shape[0] -  ad_events_clean1.shape[0] 
print(f'{removed3} records were removed, {removed3*100/ad_events.shape[0]}% from the data')

2820 records were removed, 0.705% from the data

In [32]:
tables = [users_clean, campaigns, ads, interests, ad_events_clean1, user_interest_clean, ad_interest, sub_interests]
sheet_names = ['users', 'campaigns', 'ads', 'interests', 'ad_events', 'user_interest',
               'ad_interest', 'sub_interests']
path = 'Social_Media_Campaign_Analysis_Clean.xlsx'
er =pd.ExcelWriter(path)
for i in range(len(tables)):
    tables[i].to_excel(er, sheet_name=sheet_names[i], index = False)
er.close()

# Data Segmentation

Uplode Data

In [3]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='users')
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ads')
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='campaigns')
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ad_events')
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='interests')
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='user_interest')
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='ad_interest')
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis_Clean.xlsx', sheet_name='sub_interests')

Splitting Age Ranges in the Ads Table

In [4]:
def extract_age(col_values, min_a, max_a):
    min_age_col,max_age_col = [], []

    for i in col_values:
        if i == 'All':
            min_age_col.append(min_a)
            max_age_col.append(max_a)
        else:
            min_age_col.append(int(i[:2]))
            max_age_col.append(int(i[-2:]))
    return min_age_col, max_age_col

min_age, max_age = min(users['user_age']), max(users['user_age'])
min_age_col, max_age_col = extract_age(ads['target_age_group'].values, min_age, max_age)
ads['min_age'] = min_age_col
ads['max_age'] = max_age_col
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,min_age,max_age
0,1,28,Facebook,Video,Female,35-44,35,44
1,2,33,Facebook,Stories,All,25-34,25,34
2,3,20,Instagram,Carousel,All,25-34,25,34
3,4,28,Facebook,Stories,Female,25-34,25,34
4,5,24,Instagram,Image,Female,25-34,25,34
...,...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,35,44
196,197,9,Facebook,Stories,All,All,16,65
197,198,34,Facebook,Video,All,35-44,35,44
198,199,15,Instagram,Video,Male,25-34,25,34
199,200,44,Instagram,Carousel,Male,18-24,18,24

Categorizing Ads and Users into Age Groups

In [5]:
label_dict = {'All':'All', '18-24':'Young', '25-34':'Young Adults', '35-44':'Adults'}
ads['age_group_label'] = ads['target_age_group'].map(label_dict)
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,min_age,max_age,age_group_label
0,1,28,Facebook,Video,Female,35-44,35,44,Adults
1,2,33,Facebook,Stories,All,25-34,25,34,Young Adults
2,3,20,Instagram,Carousel,All,25-34,25,34,Young Adults
3,4,28,Facebook,Stories,Female,25-34,25,34,Young Adults
4,5,24,Instagram,Image,Female,25-34,25,34,Young Adults
...,...,...,...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44,35,44,Adults
196,197,9,Facebook,Stories,All,All,16,65,All
197,198,34,Facebook,Video,All,35-44,35,44,Adults
198,199,15,Instagram,Video,Male,25-34,25,34,Young Adults
199,200,44,Instagram,Carousel,Male,18-24,18,24,Young

Categorizing Users into Age Groups

In [6]:
bins = [16, 25, 35, 45, 65]
labels = ['Young', 'Young Adults', 'Adults', 'Elderly']
users['age_label'] = pd.cut(users['user_age'],bins=bins,labels=labels,right=False,include_lowest=True)
users

,user_id,user_gender,user_age,country,location,age_label
0,a2474,Female,24,United Kingdom,New Mariomouth,Young
1,14100000,Male,21,Germany,Danielsfort,Young
2,34db0,Male,27,Australia,Vincentchester,Young Adults
3,20d08,Female,28,India,Lisaport,Young Adults
4,9e830,Male,28,United States,Brownmouth,Young Adults
...,...,...,...,...,...,...
9888,24364,Male,18,United States,Curtisside,Young
9889,68b82,Male,24,Mexico,Brownland,Young
9890,39f39,Male,29,United States,Watersburgh,Young Adults
9891,0b8e7,Male,31,United Kingdom,South Kenneth,Young Adults
9892,99e3f,Male,37,Canada,New Courtneyview,Adults

Calculating Campaign Duration

In [7]:
campaigns['Duration (Days)'] = (campaigns['end_date'] - campaigns['start_date']).dt.days
campaigns

,campaign_id,name,start_date,end_date,total_budget,Duration (Days)
0,1,Campaign_1_Launch,2025-03-25,2025-07-23,24021.32,120
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,79342.41,82
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,14343.25,56
3,4,Campaign_4_Summer,2025-04-04,2025-08-08,45326.60,126
4,5,Campaign_5_Launch,2025-05-11,2025-08-28,68376.69,109
5,6,Campaign_6_Winter,2025-04-21,2025-09-13,78607.49,145
6,7,Campaign_7_Winter,2025-03-25,2025-08-05,43744.59,133
7,8,Campaign_8_Q3,2025-02-25,2025-04-07,39953.19,41
8,9,Campaign_9_Launch,2025-03-25,2025-07-13,40094.07,110
9,10,Campaign_10_Winter,2025-03-17,2025-07-21,19669.27,126
10,11,Campaign_11_Q3,2025-04-24,2025-07-02,79067.91,69
11,12,Campaign_12_Q3,2025-03-08,2025-06-01,30525.65,85
12,13,Campaign_13_Winter,2025-04-19,2025-07-01,21855.42,73
13,14,Campaign_14_Summer,2025-04-15,2025-06-04,39849.94,50
14,15,Campaign_15_Launch,2025-03-21,2025-06-11,85407.23,82
15,16,Campaign_16_Winter,2025-03-07,2025-06-04,71521.88,89
16,17,Campaign_17_Launch,2025-04-22,2025-07-18,86675.92,87
17,18,Campaign_18_Q3,2025-04-19,2025-06-15,48832.61,57
18,19,Campaign_19_Winter,2025-03-06,2025-05-15,33182.45,70
19,20,Campaign_20_Winter,2025-02-17,2025-05-18,98904.66,90
20,21,Campaign_21_Winter,2025-04-19,2025-06-22,37290.81,64
21,22,Campaign_22_Q3,2025-03-17,2025-04-22,35743.40,36
22,23,Campaign_23_Winter,2025-05-10,2025-10-02,26001.67,145
23,24,Campaign_24_Summer,2025-03-30,2025-05-23,56692.87,54
24,25,Campaign_25_Winter,2025-04-07,2025-09-04,52725.49,150
25,26,Campaign_26_Winter,2025-04-01,2025-06-17,44538.87,77
26,27,Campaign_27_Q3,2025-02-13,2025-04-02,12986.30,48
27,28,Campaign_28_Winter,2025-03-09,2025-06-30,32844.79,113
28,29,Campaign_29_Winter,2025-05-16,2025-10-06,19773.66,143
29,30,Campaign_30_Winter,2025-02-25,2025-05-10,73911.29,74
30,31,Campaign_31_Summer,2025-03-27,2025-07-22,72208.34,117
31,32,Campaign_32_Summer,2025-05-02,2025-06-14,81744.53,43
32,33,Campaign_33_Summer,2025-04-08,2025-07-04,59264.68,87
33,34,Campaign_34_Winter,2025-05-10,2025-09-08,26104.30,121
34,35,Campaign_35_Launch,2025-05-23,2025-10-12,71626.83,142
35,36,Campaign_36_Q3,2025-03-07,2025-05-13,58801.99,67
36,37,Campaign_37_Launch,2025-03-18,2025-08-01,46445.20,136
37,38,Campaign_38_Q3,2025-04-21,2025-05-27,71038.28,36
38,39,Campaign_39_Q3,2025-03-18,2025-07-27,55638.18,131
39,40,Campaign_40_Summer,2025-03-04,2025-04-20,53936.41,47
40,41,Campaign_41_Winter,2025-04-02,2025-06-12,85220.35,71
41,42,Campaign_42_Summer,2025-04-08,2025-07-25,7918.04,108
42,43,Campaign_43_Winter,2025-04-23,2025-06-12,81350.30,50
43,44,Campaign_44_Q3,2025-05-14,2025-09-22,15914.87,131
44,45,Campaign_45_Summer,2025-03-26,2025-08-05,53303.55,132
45,46,Campaign_46_Winter,2025-03-10,2025-08-07,94023.76,150
46,47,Campaign_47_Launch,2025-04-17,2025-09-03,69493.36,139
47,48,Campaign_48_Winter,2025-04-08,2025-06-01,13842.07,54
48,49,Campaign_49_Winter,2025-02-21,2025-05-17,28962.34,85
49,50,Campaign_50_Summer,2025-05-02,2025-08-03,47274.70,93

Extracting Date and Time Features

In [8]:
ad_events['Day_Of_Week'] = ad_events['timestamp'].dt.day_name()
ad_events['Is_weekend'] = ad_events['timestamp'].dt.dayofweek >= 5
ad_events['Hour'] = ad_events['timestamp'].dt.hour
ad_events

,event_id,ad_id,user_id,timestamp,event_type,Day_Of_Week,Is_weekend,Hour
0,1,197,2359b,2025-07-26 00:19:56,Like,Saturday,True,0
1,2,51,f9c67,2025-06-15 08:28:07,Share,Sunday,True,8
2,3,46,5b868,2025-06-27 00:40:02,Impression,Friday,False,0
3,4,166,3d440,2025-06-05 19:20:45,Impression,Thursday,False,19
4,5,52,68f1a,2025-07-22 08:30:29,Impression,Tuesday,False,8
...,...,...,...,...,...,...,...,...
392931,399996,132,3cb8c,2025-08-01 22:36:54,Impression,Friday,False,22
392932,399997,200,fe0e3,2025-05-31 14:53:18,Impression,Saturday,True,14
392933,399998,2,a08c1,2025-07-27 13:39:51,Click,Sunday,True,13
392934,399999,109,4f0cf,2025-05-16 02:38:23,Impression,Friday,False,2
392935,400000,63,2c11d,2025-06-15 12:06:28,Impression,Sunday,True,12

In [9]:
from datetime import time

def get_day_part_from_time(t, day_part_dict):
    h = t
    for (start, end), label in day_part_dict.items():
        if start <= end:
            if start <= h <= end:
                return label
        else:
            if h >= start or h <= end:
                return label
    return None

In [10]:
day_part = {(6,11):'morning',(12,16):'noon', (17,22):'evening',(23,5):'night'}
ad_events['day_part'] = ad_events['Hour'].apply(
    lambda h: get_day_part_from_time(h, day_part)
)
ad_events

,event_id,ad_id,user_id,timestamp,event_type,Day_Of_Week,Is_weekend,Hour,day_part
0,1,197,2359b,2025-07-26 00:19:56,Like,Saturday,True,0,night
1,2,51,f9c67,2025-06-15 08:28:07,Share,Sunday,True,8,morning
2,3,46,5b868,2025-06-27 00:40:02,Impression,Friday,False,0,night
3,4,166,3d440,2025-06-05 19:20:45,Impression,Thursday,False,19,evening
4,5,52,68f1a,2025-07-22 08:30:29,Impression,Tuesday,False,8,morning
...,...,...,...,...,...,...,...,...,...
392931,399996,132,3cb8c,2025-08-01 22:36:54,Impression,Friday,False,22,evening
392932,399997,200,fe0e3,2025-05-31 14:53:18,Impression,Saturday,True,14,noon
392933,399998,2,a08c1,2025-07-27 13:39:51,Click,Sunday,True,13,noon
392934,399999,109,4f0cf,2025-05-16 02:38:23,Impression,Friday,False,2,night
392935,400000,63,2c11d,2025-06-15 12:06:28,Impression,Sunday,True,12,noon

# All Data

In [20]:
users = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='users')
users

,user_id,user_gender,user_age,country,location
0,a2474,Female,24,United Kingdom,New Mariomouth
1,14100000,Male,21,Germany,Danielsfort
2,34db0,Male,27,Australia,Vincentchester
3,20d08,Female,28,India,Lisaport
4,9e830,Male,28,United States,Brownmouth
...,...,...,...,...,...
9995,24364,Male,18,United States,Curtisside
9996,68b82,Male,24,Mexico,Brownland
9997,39f39,Male,29,United States,Watersburgh
9998,0b8e7,Male,31,United Kingdom,South Kenneth
9999,99e3f,Male,37,Canada,New Courtneyview

In [21]:
ads = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ads')
ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group
0,1,28,Facebook,Video,Female,35-44
1,2,33,Facebook,Stories,All,25-34
2,3,20,Instagram,Carousel,All,25-34
3,4,28,Facebook,Stories,Female,25-34
4,5,24,Instagram,Image,Female,25-34
...,...,...,...,...,...,...
195,196,12,Facebook,Stories,Male,35-44
196,197,9,Facebook,Stories,All,All
197,198,34,Facebook,Video,All,35-44
198,199,15,Instagram,Video,Male,25-34
199,200,44,Instagram,Carousel,Male,18-24

In [3]:
campaigns = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='campaigns')
campaigns

,campaign_id,name,start_date,end_date,total_budget
0,1,Campaign_1_Launch,2025-03-25,2025-07-23,24021.32
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,79342.41
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,14343.25
3,4,Campaign_4_Summer,2025-04-04,2025-08-08,45326.60
4,5,Campaign_5_Launch,2025-05-11,2025-08-28,68376.69
5,6,Campaign_6_Winter,2025-04-21,2025-09-13,78607.49
6,7,Campaign_7_Winter,2025-03-25,2025-08-05,43744.59
7,8,Campaign_8_Q3,2025-02-25,2025-04-07,39953.19
8,9,Campaign_9_Launch,2025-03-25,2025-07-13,40094.07
9,10,Campaign_10_Winter,2025-03-17,2025-07-21,19669.27
10,11,Campaign_11_Q3,2025-04-24,2025-07-02,79067.91
11,12,Campaign_12_Q3,2025-03-08,2025-06-01,30525.65
12,13,Campaign_13_Winter,2025-04-19,2025-07-01,21855.42
13,14,Campaign_14_Summer,2025-04-15,2025-06-04,39849.94
14,15,Campaign_15_Launch,2025-03-21,2025-06-11,85407.23
15,16,Campaign_16_Winter,2025-03-07,2025-06-04,71521.88
16,17,Campaign_17_Launch,2025-04-22,2025-07-18,86675.92
17,18,Campaign_18_Q3,2025-04-19,2025-06-15,48832.61
18,19,Campaign_19_Winter,2025-03-06,2025-05-15,33182.45
19,20,Campaign_20_Winter,2025-02-17,2025-05-18,98904.66
20,21,Campaign_21_Winter,2025-04-19,2025-06-22,37290.81
21,22,Campaign_22_Q3,2025-03-17,2025-04-22,35743.40
22,23,Campaign_23_Winter,2025-05-10,2025-10-02,26001.67
23,24,Campaign_24_Summer,2025-03-30,2025-05-23,56692.87
24,25,Campaign_25_Winter,2025-04-07,2025-09-04,52725.49
25,26,Campaign_26_Winter,2025-04-01,2025-06-17,44538.87
26,27,Campaign_27_Q3,2025-02-13,2025-04-02,12986.30
27,28,Campaign_28_Winter,2025-03-09,2025-06-30,32844.79
28,29,Campaign_29_Winter,2025-05-16,2025-10-06,19773.66
29,30,Campaign_30_Winter,2025-02-25,2025-05-10,73911.29
30,31,Campaign_31_Summer,2025-03-27,2025-07-22,72208.34
31,32,Campaign_32_Summer,2025-05-02,2025-06-14,81744.53
32,33,Campaign_33_Summer,2025-04-08,2025-07-04,59264.68
33,34,Campaign_34_Winter,2025-05-10,2025-09-08,26104.30
34,35,Campaign_35_Launch,2025-05-23,2025-10-12,71626.83
35,36,Campaign_36_Q3,2025-03-07,2025-05-13,58801.99
36,37,Campaign_37_Launch,2025-03-18,2025-08-01,46445.20
37,38,Campaign_38_Q3,2025-04-21,2025-05-27,71038.28
38,39,Campaign_39_Q3,2025-03-18,2025-07-27,55638.18
39,40,Campaign_40_Summer,2025-03-04,2025-04-20,53936.41
40,41,Campaign_41_Winter,2025-04-02,2025-06-12,85220.35
41,42,Campaign_42_Summer,2025-04-08,2025-07-25,7918.04
42,43,Campaign_43_Winter,2025-04-23,2025-06-12,81350.30
43,44,Campaign_44_Q3,2025-05-14,2025-09-22,15914.87
44,45,Campaign_45_Summer,2025-03-26,2025-08-05,53303.55
45,46,Campaign_46_Winter,2025-03-10,2025-08-07,94023.76
46,47,Campaign_47_Launch,2025-04-17,2025-09-03,69493.36
47,48,Campaign_48_Winter,2025-04-08,2025-06-01,13842.07
48,49,Campaign_49_Winter,2025-02-21,2025-05-17,28962.34
49,50,Campaign_50_Summer,2025-05-02,2025-08-03,47274.70

In [20]:
ad_events = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_events')
ad_events

,event_id,ad_id,user_id,timestamp,event_type
0,1,197,2359b,2025-07-26 00:19:56,Like
1,2,51,f9c67,2025-06-15 08:28:07,Share
2,3,46,5b868,2025-06-27 00:40:02,Impression
3,4,166,3d440,2025-06-05 19:20:45,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Impression
...,...,...,...,...,...
399995,399996,132,3cb8c,2025-08-01 22:36:54,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Impression

In [21]:
interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='interests')
interests

,interest_id,interest
0,1,art
1,2,technology
2,3,food
3,4,fitness
4,5,gaming
5,6,finance
6,7,lifestyle
7,8,travel
8,9,sports
9,10,health
10,11,news
11,12,fashion
12,13,photography

In [22]:
user_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='user_interest')
user_interest

,user_id,interest_id
0,a2474,4
1,a2474,10
2,14100000,3
3,14100000,4
4,14100000,7
...,...,...
19929,68b82,6
19930,39f39,10
19931,0b8e7,1
19932,0b8e7,12
19933,99e3f,4

In [23]:
ad_interest = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='ad_interest')
ad_interest

,ad_id,interest_id
0,1,1
1,1,2
2,2,8
3,2,13
4,3,2
...,...,...
295,198,4
296,198,7
297,199,1
298,199,11
299,200,13

In [24]:
sub_interests = pd.read_excel('/data/notebook_files/Social_Media_Campaign_Analysis.xlsx', sheet_name='sub_interests')
sub_interests

,interest_id,interest_id_related
0,1,12
1,1,13
2,2,6
3,2,5
4,2,11
5,2,13
6,3,7
7,3,10
8,3,4
9,4,3
10,4,9
11,4,10
12,4,7
13,5,9
14,5,2
15,6,2
16,6,11
17,7,8
18,7,12
19,7,10
20,7,4
21,8,13
22,8,7
23,9,4
24,9,11
25,9,10
26,9,5
27,10,4
28,10,9
29,10,7
30,10,3
31,11,2
32,11,9
33,11,6
34,12,1
35,12,7
36,13,1
37,13,8
38,13,2